# Generated by Django 6.0.3 on 2026-04-04 17:04

import django.contrib.auth.models
import django.contrib.auth.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='BiayaBongkar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_no', models.CharField(max_length=20)),
                ('doc_fee', models.IntegerField(default=0)),
                ('cleaning', models.IntegerField(default=0)),
                ('thc_bongkar', models.IntegerField(default=0)),
                ('lolo_bongkar', models.IntegerField(default=0)),
                ('stripping_dalam', models.IntegerField(default=0)),
                ('trucking', models.IntegerField(default=0)),
                ('buruh', models.IntegerField(default=0)),
                ('materai', models.IntegerField(default=0)),
                ('ops', models.IntegerField(default=0)),
                ('tally_bongkar', models.IntegerField(default=0)),
                ('alat', models.IntegerField(default=0)),
                ('fee', models.IntegerField(default=0)),
                ('door_service', models.IntegerField(default=0)),
                ('by_lain', models.IntegerField(default=0)),
                ('by_lain_2', models.IntegerField(default=0)),
                ('by_lain_3', models.IntegerField(default=0)),
                ('tot_by_bongkar', models.IntegerField(default=0)),
                ('vendor_muat', models.CharField(blank=True, max_length=100)),
                ('panduan_muat', models.CharField(blank=True, max_length=100)),
                ('vendor_bongkar', models.CharField(blank=True, max_length=100)),
                ('panduan_bongkar', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'db_table': 'biaya_bongkar',
            },
        ),
        migrations.CreateModel(
            name='BiayaMuat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_no', models.CharField(max_length=20)),
                ('inc', models.BooleanField(default=True)),
                ('tertanggung', models.CharField(max_length=100)),
                ('persen', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('premi', models.IntegerField(default=0)),
                ('bl_fee', models.IntegerField(default=0)),
                ('seal', models.IntegerField(default=0)),
                ('freight', models.IntegerField(default=0)),
                ('lss', models.IntegerField(default=0)),
                ('toeslag', models.IntegerField(default=0)),
                ('alur', models.IntegerField(default=0)),
                ('thc_muat', models.IntegerField(default=0)),
                ('lolo_muat', models.IntegerField(default=0)),
                ('stuffing', models.IntegerField(default=0)),
                ('damage', models.IntegerField(default=0)),
                ('trucking', models.IntegerField(default=0)),
                ('ops', models.IntegerField(default=0)),
                ('tally', models.IntegerField(default=0)),
                ('lain_1', models.IntegerField(default=0)),
                ('lain_2', models.IntegerField(default=0)),
                ('total_biaya', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'biaya_muat',
            },
        ),
        migrations.CreateModel(
            name='resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consignee', models.CharField(max_length=100)),
                ('alamat_bongkar', models.TextField()),
                ('tarif_jasa_kirim', models.IntegerField()),
                ('ppn', models.IntegerField(default=0)),
                ('pph', models.IntegerField(default=0)),
                ('pph23', models.IntegerField(default=0)),
                ('total', models.IntegerField(default=0)),
                ('total_biaya', models.IntegerField(default=0)),
                ('profit', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'resume',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('nomor_sales', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'auth_user',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
