# Generated by Django 6.0.3 on 2026-04-04 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BiayaMuat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_no', models.CharField(max_length=20)),
                ('inc', models.BooleanField(default=True)),
                ('tertanggung', models.CharField(max_length=100)),
                ('persen', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('premi', models.IntegerField(default=0)),
                ('bl_fee', models.IntegerField(default=0)),
                ('seal', models.IntegerField(default=0)),
                ('freight', models.IntegerField(default=0)),
                ('lss', models.IntegerField(default=0)),
                ('toeslag', models.IntegerField(default=0)),
                ('alur', models.IntegerField(default=0)),
                ('thc_muat', models.IntegerField(default=0)),
                ('lolo_muat', models.IntegerField(default=0)),
                ('stuffing', models.IntegerField(default=0)),
                ('damage', models.IntegerField(default=0)),
                ('trucking', models.IntegerField(default=0)),
                ('ops', models.IntegerField(default=0)),
                ('tally', models.IntegerField(default=0)),
                ('lain_1', models.IntegerField(default=0)),
                ('lain_2', models.IntegerField(default=0)),
                ('total_biaya', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'biaya_muat',
            },
        ),
    ]
