# Generated by Django 6.0.3 on 2026-04-06 12:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_biayabongkar_user_biayamuat_user_resume_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode_customer', models.CharField(max_length=20, unique=True)),
                ('nama_customer', models.CharField(max_length=200)),
                ('sales', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'customer',
            },
        ),
        migrations.AddField(
            model_name='biayabongkar',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='biaya_bongkars', to='app.customer'),
        ),
        migrations.AddField(
            model_name='biayamuat',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='biaya_muats', to='app.customer'),
        ),
        migrations.AddField(
            model_name='resume',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resumes', to='app.customer'),
        ),
    ]
