# Generated by Django 6.0.3 on 2026-04-06 13:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_customer_biayabongkar_customer_biayamuat_customer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='sales',
        ),
        migrations.AddField(
            model_name='biayabongkar',
            name='bulan',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='biayabongkar',
            name='tahun',
            field=models.IntegerField(default=2024),
        ),
        migrations.AddField(
            model_name='biayamuat',
            name='bulan',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='biayamuat',
            name='tahun',
            field=models.IntegerField(default=2024),
        ),
        migrations.AddField(
            model_name='customer',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='customer',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='bulan',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='resume',
            name='tahun',
            field=models.IntegerField(default=2024),
        ),
    ]
