# Generated by Django 6.0.3 on 2026-04-06 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_customer_sales_biayabongkar_bulan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='pod',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='pol',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
