# Generated by Django 6.0.3 on 2026-04-06 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_customer_pod_customer_pol'),
    ]

    operations = [
        migrations.AddField(
            model_name='biayabongkar',
            name='pod',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='biayabongkar',
            name='pol',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='biayamuat',
            name='pod',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='biayamuat',
            name='pol',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='pod',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='pol',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
